general {
    grace = 0
    hide_cursor = true
    no_fade_in = false
}

background {
    monitor =
    path = /home/ball/Pictures/wallpapers/leonardo-yip-NcWnJmeVtcw-unsplash.jpg   # or screenshot
    blur_passes = 0
    contrast = 1
    brightness = 0.8172
    vibrancy = 0.2
    vibrancy_darkness = 0.4
}


label {
    monitor =
    text = cmd[update:997] TZ=Europe/Vienna date +"%H:%M"
    font_size = 120
    position = 0, 10
    halign = center
    valign = center
}
