general {
    grace = 0
    hide_cursor = true
    no_fade_in = false
}

background {
    monitor =
    path = ~/Pictures/wallpapers/cristina-gottardi-CSpjU6hYo_0-unsplash.jpg   # or screenshot
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}


label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 120
    position = 0, 80
    halign = center
    valign = center
}
